version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 80:3000  
    environment:
      - NODE_ENV=production
      - PORT=3000
    # command:
    #   sh -c 'npm i && npm run start'